import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { readFile, writeFile, mkdtemp, mkdir, realpath, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import os from 'node:os';
import { defaultUnifiedConfig } from '../dist/src/config.js';
const root=fileURLToPath(new URL('../',import.meta.url));
if(process.argv.slice(2).some(arg=>arg!=='--check'))throw new Error('Usage: node scripts/export-tools.mjs [--check]');
const check=process.argv.includes('--check');
const client=new Client({name:'webcodex-schema-export',version:'1.0'});
// Schema export must not acquire the running tunnel service's SQLite lease.
const tempRoot=await realpath(os.tmpdir());
const temporary=await mkdtemp(path.join(tempRoot,'webcodex-schema-'));
try {
 const workspace=path.join(temporary,'workspace');
 await mkdir(workspace);
 const configPath=path.join(temporary,'config.json');
 await writeFile(configPath,JSON.stringify(defaultUnifiedConfig(workspace,configPath,{deviceName:'Example device'}))+'\n');
 await client.connect(new StdioClientTransport({command:process.execPath,args:[path.join(root,'dist/src/cli.js'),'serve','--config',configPath],stderr:'inherit'}));
 const result=await client.listTools();
 const content=JSON.stringify({server:client.getServerVersion(),tools:result.tools},null,2)+'\n';
 const privateCount=result.tools.filter(tool=>tool._meta?.['openai/visibility']==='private').length;
 const acceptance=`<!-- Generated by npm run export:tools; do not edit. -->\n# 当前版本验收入口\n\n版本：\`${client.getServerVersion().version}\`。注册工具 **${result.tools.length}** 项，其中普通工具 **${result.tools.length-privateCount}** 项、组件私有工具 **${privateCount}** 项。当前聊天能否实际调用仍需验证。\n\n> 使用 WebCodex，调用 system_status 和 workspace_list，确认版本为 ${client.getServerVersion().version}，核实目标设备、工作区和权限。用 fs_write 创建一个中文文本文件，再用 fs_read 读回核对。本机文件复制直接用 fs_stat 取得源哈希，再用 fs_copy 传源/目标工作区和相对路径；不上传、不导入、不执行脚本，最后 fs_stat 核对目标。对本地 PDF 使用 document_open/document_read，仅从 ready 页正文回答。生成原文件使用 fs_save_file：提交当前产物的真实宿主文件 ID 或官方文件对象、原件大小和 SHA-256；已有目标先 fs_stat 核实旧哈希。不传 Base64、不提供手填 URL、不缩图或重新生成。保持自动组件打开，用 fs_save_file_status 按 retry_after_ms 和 can_poll 查询；仅 status=saved 且 verified=true 后再用 fs_stat 对比原件。失败/unknown 停止，使用同一键查询 operation_status（tool=fs_import_file），不盲目重写。只有 sandbox 路径或宿主未授权时如实报告，不能猜测文件 ID。\n\n工具成功、本机文件存在和 ChatGPT 实际读到正文需要分别取证。组件与服务集成测试不能证明真实宿主已授权当前生成文件；旧 Base64 路线已出现截断，新文件 ID 路线仍需真实验收，详情见[回存说明](file-writeback.md)。请在隔离测试目录完成验收，不用已有私人文件作为公开测试材料。\n`;
 const target=path.join(root,'docs/tools.json');
 const acceptanceTarget=path.join(root,'docs/current-acceptance.md');
 if(check){
   if((await readFile(target,'utf8')).replaceAll('\r\n','\n')!==content)throw new Error('Tool documentation is stale. Build and run npm run export:tools.');
   if((await readFile(acceptanceTarget,'utf8')).replaceAll('\r\n','\n')!==acceptance)throw new Error('Acceptance documentation is stale. Run npm run export:tools.');
 }else { await writeFile(target,content); await writeFile(acceptanceTarget,acceptance); }
 console.log((check?'Verified ':'Exported ')+result.tools.length+' tools in docs/tools.json');
}finally{
 try { await client.close(); }
 finally {
  const actual=await realpath(temporary);
  if(path.dirname(actual)!==tempRoot || !path.basename(actual).startsWith('webcodex-schema-'))throw new Error('Refusing cleanup outside the schema export directory.');
  await rm(actual,{recursive:true,force:true});
 }
}
