/** Fixed component diagnostics only: no document bytes, paths, URLs or exception messages. */
export const DOCUMENT_FAILURE_CODES = ['PDF_INVALID', 'PDF_PASSWORD_REQUIRED', 'PDF_PARSE_FAILED', 'FILE_INTEGRITY_ERROR', 'PDF_LIMIT', 'ASSET_UNAVAILABLE'] as const;

export const DOCUMENT_DIAGNOSTIC_PHASES = ['file', 'parse', 'extract'] as const;

export const DOCUMENT_DIAGNOSTIC_CODES = [
  ...DOCUMENT_FAILURE_CODES, 'HOST_TIMEOUT', 'HOST_UNAVAILABLE', 'INVALID_RESPONSE', 'INVALID_METADATA',
  'UNSUPPORTED_PROTOCOL', 'DOCUMENT_EXPIRED', 'DOCUMENT_ACCESS_DENIED', 'DOCUMENT_NOT_FOUND', 'DOCUMENT_STALE_SUBMISSION',
  'DOCUMENT_ASSET_INVALID', 'DOCUMENT_ASSET_UNAVAILABLE', 'DOCUMENT_ASSET_LIMIT', 'DEVICE_MISMATCH',
  'WORKSPACE_DISABLED', 'WORKSPACE_UNAVAILABLE', 'WORKSPACE_NOT_FOUND', 'SNAPSHOT_EXPIRED', 'FILE_CHANGED', 'FILE_TOO_LARGE',
  'UNKNOWN_ERROR', 'JSON_RPC_ERROR',
] as const;

export const DOCUMENT_DIAGNOSTIC_DETAILS = [
  'RESULT_WRAPPER_LIMIT', 'RESULT_CONFLICT', 'RESULT_IDENTITY_MISMATCH', 'PRIVATE_BYTES_MISSING',
  'FILE_SIZE_INVALID', 'CHUNK_METADATA_INVALID', 'BASE64_LENGTH_MISMATCH', 'BASE64_FORMAT_INVALID',
  'FILE_TOTAL_MISMATCH', 'FILE_HASH_METADATA_MISMATCH', 'BASE64_DECODE_FAILED', 'DECODED_SIZE_MISMATCH',
  'BASE64_ROUNDTRIP_MISMATCH', 'CHUNK_SHA256_MISMATCH', 'CHUNK_END_MISMATCH', 'FILE_SHA256_MISMATCH',
  'ASSET_KIND_UNSUPPORTED', 'ASSET_NAME_UNSUPPORTED', 'ASSET_BYTES_INVALID',
] as const;

// The running component may predate the server; a bounded numeric version preserves that evidence.
export const DOCUMENT_COMPONENT_VERSION_MAX_LENGTH = 40;
export const DOCUMENT_COMPONENT_VERSION_PATTERN = /^(?:0|[1-9]\d{0,2})\.(?:0|[1-9]\d{0,2})\.(?:0|[1-9]\d{0,2})(?:-preview\.(?:0|[1-9]\d{0,3}))?(?![\s\S])/;

export interface DocumentFailureDiagnostics {
  component_version: string;
  phase: typeof DOCUMENT_DIAGNOSTIC_PHASES[number];
  code: typeof DOCUMENT_DIAGNOSTIC_CODES[number];
  detail_code?: typeof DOCUMENT_DIAGNOSTIC_DETAILS[number];
}
