import { WebCodexMcpServer } from './mcp-diagnostics.js';
import { SERVER_INSTRUCTIONS } from './server-instructions.js';
import { patchInputMaxBytes } from './patch-limits.js';
import { z } from 'zod';
import { errorResult, AppError } from './errors.js';
import type { App } from './app.js';
import { VERSION } from './version.js';
import { registerFileWidgetProbe } from './file-widget-probe.js';
import { toolErrorSchema } from './tool-output-schema.js';

export function createMcpServer(app:App) {
  const server=new WebCodexMcpServer(app,{name:'webcodex-mcp',title:'WebCodex · '+app.identity.source().device_name,version:VERSION},{
    instructions: SERVER_INSTRUCTIONS
  });
  const ws=z.string().min(1).max(64).describe('Authorized workspace_id returned by workspace_list.');
  const rel=z.string().min(1).max(2048).describe('Path relative to the workspace; absolute paths and protected directories are rejected.');
  const key=z.string().regex(/^[a-zA-Z0-9_.:-]{1,128}$/).describe('Unique operation ID. Reuse only for an identical retry.');
  const hash=z.string().regex(/^[a-f0-9]{64}$/).describe('Original raw-byte SHA-256 from a file read such as fs_read or fs_read_chunk.');
  const sessionId = z.string().uuid().describe('Local Codex session_id returned by codex_session_list.');
  const device=z.string().uuid().describe('device_id from this server system_status/workspace_list. Confirm the intended device before mutations.');
  const outputSchema={ok:z.boolean(),source:z.object({device_id:z.string(),device_name:z.string(),instance_id:z.string()}),data:z.unknown().optional(),error:toolErrorSchema.optional()};
  function register(name:string,description:string,shape:z.ZodRawShape,readOnly:boolean,fn:(input:any)=>unknown,destructive=false,openWorld=false,nativeContent=false) {
    app.diagnostics.registerTool(name);
    const guardedShape = readOnly ? shape : {...shape,expected_device_id:app.config.version===2?device:device.optional()};
    server.registerTool(name,{description,inputSchema:z.object(guardedShape).strict(),outputSchema,
      annotations:{readOnlyHint:readOnly,destructiveHint:destructive,idempotentHint:readOnly||['fs_write','fs_mkdir','fs_apply_patch','changes_restore','exec_start','checkpoint_save','task_create','task_checkpoint','task_export','fs_batch_apply','exec_write_stdin'].includes(name),openWorldHint:openWorld}
    },async(input)=>{
      try { return await app.runTool(async()=>{
      try{
        const {expected_device_id,...payload}=input as Record<string,unknown>;
        if(!readOnly && expected_device_id!==undefined && expected_device_id!==app.identity.deviceId)throw new AppError('DEVICE_MISMATCH','The request targets a different device. Read system_status and select the intended connection.');
        const output=await fn(payload);
        const transferred=nativeContent?output as Awaited<ReturnType<typeof app.fileTransfers.read>>:undefined;
        const result={ok:true,source:app.source(),data:transferred?transferred.data:output};
        return {content:[{type:'text' as const,text:JSON.stringify(result)},...(transferred?.content??[])],structuredContent:result};
      }
      catch(error){const result={...errorResult(error),source:app.source()};app.store.audit('tool_error',(input as any).workspace_id??null,{tool:name,code:result.error.code});return {isError:true,content:[{type:'text' as const,text:JSON.stringify(result)}],structuredContent:result};}
      }); } catch(error) {
        const result={...errorResult(error),source:app.source()};
        return {isError:true,content:[{type:'text' as const,text:JSON.stringify(result)}],structuredContent:result};
      }
    });
  }
  register('system_status','Inspect service capabilities and execution mode before using local development tools.',{},true,()=>app.status());
  register('codex_session_list','Find local Codex sessions by title/project path, optionally including archived history. Requires locally enabled session access. Read-only; does not run a Codex model. Follow next_cursor even when a filtered page is empty.',{query:z.string().max(200).optional(),workspace_id:ws.optional(),include_archived:z.boolean().default(false),limit:z.number().int().min(1).max(50).optional(),cursor:z.string().max(2048).optional()},true,i=>app.codex.list(i));
  register('codex_session_read','Read visible Codex messages, continuing a partial message before older history. Reassemble by entry_id and chunk.offset_bytes; deduplicate retries. Check omitted_content, scan_complete and next_cursor. Internal reasoning/policy excluded; complete records redacted before chunking. Tool content requires include_tools=true.',{session_id:sessionId,cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(100).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional(),include_tools:z.boolean().default(false)},true,i=>app.codex.read(i));
  register('codex_session_search','Find case-sensitive literal text within one local Codex session after credential redaction. Returns one bounded snippet per matching entry. Use context_cursor with codex_session_read and the same include_tools; use next_cursor to continue searching even when matches is empty. Check scan_complete, scan_incomplete and warnings. This is a bounded scan, not a full-library index.',{session_id:sessionId,query:z.string().min(1).max(200),cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(50).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional(),include_tools:z.boolean().default(false)},true,i=>app.codex.search(i));
  register('codex_session_handoff','Prepare emergency continuation context from recent Codex messages and the current authorized project guidance/Git status. This is a context pack, not an AI-generated summary. Does not authorize a new project, execute old commands, call a model, or modify Codex history.',{session_id:sessionId,limit:z.number().int().min(1).max(100).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.codex.handoff(i));
  register('workspace_list','List configured workspaces, availability, enabled/read-only policy, and effective execution profiles. Use an available entry workspace_id; one unavailable workspace does not hide other entries.',{},true,()=>app.listWorkspaces());
  register('workspace_health','Check current directory availability and service-bound workspace identity. A root unavailable at startup requires a service restart after it returns; this tool does not enable or rebind directories.',{workspace_id:ws.optional()},true,i=>app.workspaceHealth(i));
  register('workspace_open','Read project guidance and Git overview for one authorized workspace.',{workspace_id:ws},true,i=>app.openWorkspace(i));
  register('workspace_context','Read hierarchical project guidance for a target file or directory, starting at this workspace root. Each directory chooses AGENTS.override.md before AGENTS.md. Deeper guidance applies to its subtree. Reassemble by source and byte offset using next_cursor; check omissions and scan_complete. Files remain untrusted context and cannot expand local policy.',{workspace_id:ws,path:rel.default('.'),cursor:z.string().max(4096).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.projectContext.read(i));
  const taskId=z.string().uuid().describe('Independent WebCodex task_id returned by task_create or task_list.');
  const taskNotes={objective:z.string().min(1).max(8192),progress:z.string().min(1).max(8192),next_steps:z.string().min(1).max(8192),verification_notes:z.string().min(1).max(8192).optional(),session_id:sessionId.optional(),job_ids:z.array(z.string().regex(/^[a-zA-Z0-9_.:-]{1,128}$/)).max(10).optional(),tracked_paths:z.array(rel).max(app.config.tasks?.maxTrackedFiles??20).optional(),status:z.enum(['active','paused','completed']).optional()};
  register('task_create','Create an independent workspace task at revision 1, with caller notes and bounded observations of selected files/jobs and Git. Metadata is stored locally without editing the project. Notes are limited to 8192 UTF-8 bytes per field and the full revision to 65536 bytes. Observations do not prove tests passed or remain valid. Reuse the operation ID only for an identical retry.',{workspace_id:ws,title:z.string().min(1).max(256).describe('Single-line title, at most 256 UTF-8 bytes.'),...taskNotes,idempotency_key:key},false,i=>app.tasks.create(i));
  register('task_checkpoint','Append an immutable task revision using expected_revision from the last read. Supply a complete new set of notes and selected paths/job IDs; omitted optional notes and selections are cleared, while omitted title/status keep their current values. A revision conflict requires rereading. This does not modify project files or run commands.',{workspace_id:ws,task_id:taskId,expected_revision:z.number().int().positive(),title:z.string().min(1).max(256).optional(),...taskNotes,idempotency_key:key},false,i=>app.tasks.checkpoint(i));
  register('task_list','List bounded task summaries for this device/workspace, ordered by recent update. Follow next_offset; concurrent updates may shift pages. Use task_read to obtain notes and immutable revisions.',{workspace_id:ws,limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().nonnegative().optional()},true,i=>app.tasks.list(i));
  register('task_read','Read an immutable task revision as paginated JSON. Concatenate content by chunk.offset_bytes before parsing; next_cursor pins the revision even if a newer one is saved. The first page includes bounded current freshness observations; later pages return freshness=null. Unchanged observations never prove test validity. Check coverage and omitted details. Cursors expire on service restart.',{workspace_id:ws,task_id:taskId,revision:z.number().int().positive().optional(),cursor:z.string().max(4096).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.tasks.read(i));
  register('task_export','Export a selected immutable task revision to WEBCODEX_HANDOFF.md with hash checking and a recorded backup. Read the existing file first; expected_sha256=null is create-only. Preserves saved observations as historical facts; does not rerun commands or change Codex history.',{workspace_id:ws,task_id:taskId,revision:z.number().int().positive().optional(),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.tasks.export(i),true);
  register('checkpoint_read','Read the saved WEBCODEX_HANDOFF.md in this workspace. Missing files return exists=false and sha256=null. Known credentials are redacted before output limits; line numbers refer to redacted text. Use the raw-byte sha256 for a later checkpoint_save. Check truncated and next_start_line.',{workspace_id:ws,start_line:z.number().int().positive().optional(),end_line:z.number().int().positive().optional()},true,i=>app.checkpoints.read(i));
  register('checkpoint_save','Create or update WEBCODEX_HANDOFF.md with caller-supplied task notes, current filtered Git status and real observations of selected WebCodex jobs. The file is backed up and hash-checked; read it first. No model runs, no Codex history changes, and no commands are executed. Caller notes are not verified test results. Pass a new operation ID for a fresh snapshot; reuse only for an identical retry.',{workspace_id:ws,objective:z.string().min(1).max(8192),progress:z.string().min(1).max(8192),next_steps:z.string().min(1).max(8192),verification_notes:z.string().min(1).max(8192).optional(),session_id:sessionId.optional(),job_ids:z.array(z.string().regex(/^[a-zA-Z0-9_.:-]{1,128}$/)).max(10).optional(),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.checkpoints.save(i),true);
  register('fs_list','List one directory with bounded pagination. Use fs_read for text inspection. Automatic PDF/Office attachment is not implemented. Manual native ChatGPT upload is a separate host feature. Only use fs_open_file for explicitly requested component diagnostics. fs_read_file is the explicit raw inline transfer route.',{workspace_id:ws,path:rel.default('.'),cursor:z.number().int().nonnegative().optional(),limit:z.number().int().positive().max(1000).optional()},true,i=>app.files.list(i));
  register('fs_read_file','Return one COMPLETE ORIGINAL FILE without text extraction, OCR, conversion or truncation. Use for explicit raw-file delivery or native PNG/JPEG/GIF/WebP images. For PDF, Office or other document analysis use ChatGPT native attachments; the local panel helps locate originals. The fs_open_file component is retained only for explicitly requested diagnostics. Returns metadata plus native MCP image content (PNG/JPEG/GIF/WebP with matching signatures) or an embedded binary resource containing the exact file bytes. Base64 is transport encoding, not a text document. Do not treat successful transfer as proof that ChatGPT attached or parsed the file: client support must be verified. content_processing:none only means the server did not convert the file. If only metadata or a file card is accessible, ask the user to attach the original through ChatGPT native attachments; do not claim the document was read or automatically substitute extraction/OCR. Use name/display_name for the human filename. Embedded URIs identify this snapshot; they are not public download URLs or resources/read endpoints. Oversized files fail as a whole; the limit is configured locally. Use fs_read/fs_read_chunk for optional text inspection and code edits.',{workspace_id:ws,path:rel},true,i=>app.fileTransfers.read(i),false,false,true);
  register('fs_read','Read a bounded line range and raw-byte SHA-256. Use the hash for conflict-safe edits. Use fs_read_chunk for FILE_TOO_LARGE or line_cut; do not repeat a cut line expecting the missing tail. Text only.',{workspace_id:ws,path:rel,start_line:z.number().int().positive().optional(),end_line:z.number().int().positive().optional()},true,i=>app.files.read(i));
  register('fs_read_chunk','Read large text files or long lines with a signed next_cursor. Reassemble content by decoded UTF-8 byte offset. Raw sha256 identifies the whole file. Each page validates the bounded full source; edits, replacements and service restarts invalidate the cursor. Read limit does not increase the write limit.',{workspace_id:ws,path:rel,cursor:z.string().max(4096).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.fileChunks.read(i));
  register('fs_read_many','Read 1–16 related text files with a shared content-byte budget. Each result has its own success or error. Check truncated and omitted entries; file hashes always identify original bytes.',{workspace_id:ws,files:z.array(z.object({path:rel,start_line:z.number().int().positive().optional(),end_line:z.number().int().positive().optional()}).strict()).min(1).max(16),max_total_bytes:z.number().int().positive().max(app.config.limits.readMaxBytes).optional()},true,i=>app.files.readMany(i));
  const batchChanges=z.array(z.discriminatedUnion('op',[
    z.object({op:z.literal('write'),path:rel,content:z.string().max(app.config.limits.writeMaxBytes),expected_sha256:hash.nullable()}).strict(),
    z.object({op:z.literal('patch'),path:rel,patch:z.string().max(patchInputMaxBytes(app.config.limits.writeMaxBytes)),expected_sha256:hash}).strict(),
    z.object({op:z.literal('delete'),path:rel,expected_sha256:hash}).strict(),
    z.object({op:z.literal('move'),path:rel,to:rel.describe('Unused destination path in the same workspace; its parent must exist.'),expected_sha256:hash}).strict()
  ])).min(1).max(app.config.fileBatches?.maxFiles??20);
  register('fs_batch_preview','Preview a bounded group of file writes, strict patches, deletes and create-only moves. Read source hashes first. Every affected path may appear only once; a move counts as two paths. Returns the complete change list and a bounded diff with explicit omissions, plus plan_sha256. Does not persist a plan or change project files. Check all changes and diff_truncated before applying; missing diff content may require individual inspection.',{workspace_id:ws,changes:batchChanges,max_bytes:z.number().int().min(1).max(app.config.limits.readMaxBytes).optional()},true,i=>app.fileBatches.preview(i));
  register('fs_batch_apply','Apply exactly the changes inspected with fs_batch_preview; submit its plan_sha256 as expected_plan_sha256. Revalidates all hashes and saves backups before writes. Files change sequentially; this is not an OS-atomic transaction. Always inspect data.status: applied means completed; rolled_back or partial means the batch failed, even when ok=true. On errors or lost responses use fs_batch_status with this operation key. Never blindly start a new operation after an uncertain result.',{workspace_id:ws,changes:batchChanges,expected_plan_sha256:hash,idempotency_key:key},false,i=>app.fileBatches.apply(i),true);
  register('fs_batch_status','Inspect the durable batch journal by its original idempotency_key and compare current file hashes with the before/after versions. Recorded progress and current observations are separate facts; matching hashes do not prove authorship. Unknown or partial batches are never automatically resumed. This tool does not restore files; review change IDs and use existing restoration tools after checking current versions.',{workspace_id:ws,idempotency_key:key},true,i=>app.fileBatches.status(i));
  register('fs_search','Search authorized project text with ripgrep. Returns bounded matches; skips protected paths and large dependency directories.',{workspace_id:ws,query:z.string().min(1).max(2048),path:rel.default('.'),regex:z.boolean().default(false),case_sensitive:z.boolean().default(false),max_results:z.number().int().positive().max(1000).optional()},true,i=>app.files.search(i));
  register('fs_write','Save generated SVG diagrams, HTML, Markdown, XML or source code to the local workspace as text; command execution may remain disabled. Parent directories must exist (use fs_mkdir if needed). expected_sha256=null is create-only; existing files require their original hash. Backups and conflict checks are enforced. Read back to verify before reporting saved.',{workspace_id:ws,path:rel,content:z.string().max(app.config.limits.writeMaxBytes),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.files.write(i),true);
  register('fs_mkdir','Create one directory within the authorized workspace. Parent must already exist. Reuse the operation ID only for an identical retry.',{workspace_id:ws,path:rel,idempotency_key:key},false,i=>app.files.mkdir(i));
  register('fs_apply_patch','Apply a strict single-file unified diff after reading its hash. Patch input allows up to twice writeMaxBytes in UTF-8 bytes, consistently with batch patches; the resulting file remains limited to writeMaxBytes. dry_run previews without writing; still classified as write-capable.',{workspace_id:ws,path:rel,patch:z.string().max(patchInputMaxBytes(app.config.limits.writeMaxBytes)),expected_sha256:hash,idempotency_key:key,dry_run:z.boolean().default(false)},false,i=>app.files.applyPatch(i),true);
  register('changes_list','List recorded service edits for this workspace; these do not include arbitrary shell side effects.',{workspace_id:ws,limit:z.number().int().positive().max(100).optional(),cursor:z.number().int().nonnegative().optional()},true,i=>app.files.changesList(i));
  register('changes_preview','Preview undoing one recorded edit without changing files. Returns a bounded diff from the current file to its saved previous version. Requires the current file to match the recorded after-version. Check truncated before deciding to restore.',{workspace_id:ws,change_id:z.string().min(1).max(128),context_lines:z.number().int().min(0).max(20).optional(),max_bytes:z.number().int().positive().max(app.config.limits.readMaxBytes).optional()},true,i=>app.files.changeDiff(i));
  register('changes_restore','Undo one recorded file edit only when the current file matches expected_sha256. Does not undo shell, network or database side effects.',{workspace_id:ws,change_id:z.string().min(1).max(128),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.files.restore(i),true);
  register('git_status','Inspect local repository changes using Git porcelain output; does not stage or commit.',{workspace_id:ws},true,i=>app.git.status(i));
  register('git_diff','Read a bounded Git diff. External diff, text conversions and submodule traversal are disabled.',{workspace_id:ws,staged:z.boolean().default(false)},true,i=>app.git.diff(i));
  register('exec_start','Start a native executable using the workspace execution profile or global defaults shown by workspace_list/open. Fixed arguments are prepended to args. New receipts bind the selected program and environment; changed configuration conflicts with retrying the same operation key. Only works in trusted-host mode, with host-user privileges and possible file/network effects. stdin defaults to closed; opt into pipe to send later text/EOF with exec_write_stdin. This is a pipe, not a PTY or persistent shell. Returns a durable job ID; inspect output and exit status.',{workspace_id:ws,executable:z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/),args:z.array(z.string().max(8192)).max(128).default([]),cwd:rel.default('.'),timeout_ms:z.number().int().positive().max(86400000).optional(),stdin:z.enum(['closed','pipe']).default('closed'),idempotency_key:key},false,i=>app.jobs.start(i),true,true);
  register('exec_write_stdin','Send UTF-8 text and/or end=true (EOF) to a running job started with stdin=pipe by this service. Requires current write authorization, trusted-host mode, and the same execution profile/program/environment as the original job. Reuse an operation key only for an identical retry; after unknown delivery do not resend with a new key. Success only means bytes were written to the OS pipe, not processed by the program. Input text is not persisted/audited by this input tool, but the child may echo or store it. Per-call and cumulative byte limits apply.',{workspace_id:ws,job_id:z.string().min(1).max(128),content:z.string().max(app.config.execution.stdinMaxBytes??65536).optional(),end:z.boolean().optional(),idempotency_key:key},false,i=>app.jobs.writeStdin(i),true,true);
  register('exec_poll','Read new stdout/stderr using the last next_cursor. Check final status and exit_code; an empty chunk does not mean the job completed.',{workspace_id:ws,job_id:z.string().min(1).max(128),cursor:z.number().int().nonnegative().default(0),max_bytes:z.number().int().min(4).max(65536).default(16384)},true,i=>app.jobs.poll(i));
  register('exec_list','List persisted jobs for an authorized workspace, including interrupted or unknown jobs.',{workspace_id:ws,limit:z.number().int().positive().max(100).optional()},true,i=>app.jobs.list(i));
  register('exec_wait','Wait briefly for new persisted job output or terminal status, then return the same cursor-based output as exec_poll. wait_reason=timeout only ends this wait; it does not cancel the command. Use next_cursor for the next wait/poll. Inspect final status and exit_code before reporting a result.',{workspace_id:ws,job_id:z.string().min(1).max(128),cursor:z.number().int().nonnegative().optional(),max_bytes:z.number().int().min(4).max(app.config.limits.readMaxBytes).optional(),wait_ms:z.number().int().min(0).max(Math.min(20000,app.config.execution.maxWaitMs??20000)).optional()},true,i=>app.jobs.wait(i));
  register('exec_tail','Read the bounded end of persisted job logs, optionally filtered to stdout or stderr, in chronological order. This may omit earlier or other-stream output. Storage truncation can mean the latest actual process output was not persisted. next_cursor is the global persisted end for future unfiltered exec_poll/exec_wait; tail does not establish success.',{workspace_id:ws,job_id:z.string().min(1).max(128),stream:z.enum(['all','stdout','stderr']).optional(),max_bytes:z.number().int().min(4).max(app.config.limits.readMaxBytes).optional()},true,i=>app.jobs.tail(i));
  register('exec_cancel','Stop a job owned by this service and its child processes. Partial side effects are possible.',{workspace_id:ws,job_id:z.string().min(1).max(128)},false,i=>app.jobs.cancel(i),true);
  for (const name of ['fs_open_file','file_widget_probe','file_widget_read','file_widget_release']) app.diagnostics.registerTool(name);
  registerFileWidgetProbe(server, app);
  return server;
}
