import { WebCodexMcpServer } from './mcp-diagnostics.js';
import { SERVER_INSTRUCTIONS } from './server-instructions.js';
import { FILE_ROUTES, MODEL_RELAY_GUIDANCE } from './file-routing.js';
import { patchInputMaxBytes } from './patch-limits.js';
import { z } from 'zod';
import { errorResult, AppError } from './errors.js';
import type { App } from './app.js';
import { VERSION } from './version.js';
import { registerFileWidgetProbe } from './file-widget-probe.js';
import { toolErrorSchema } from './tool-output-schema.js';
import { registerReadingRelayProbe } from './reading-relay-probe.js';
import { registerDocumentTools } from './document-tools.js';
import { registerFileSaveTools } from './file-save-tools.js';
import { chatGptFileSchema } from './file-import.js';
import { binaryChunkLimits } from './binary-limits.js';

export function createMcpServer(app:App) {
  const server=new WebCodexMcpServer(app,{name:'webcodex-mcp',title:'WebCodex · '+app.identity.source().device_name,version:VERSION},{
    instructions: SERVER_INSTRUCTIONS
  });
  const ws=z.string().min(1).max(64).describe('Authorized workspace_id returned by workspace_list.');
  const rel=z.string().min(1).max(2048).describe('Path relative to the workspace; absolute paths and protected directories are rejected.');
  const key=z.string().regex(/^[a-zA-Z0-9_.:-]{1,128}$/).describe('Unique operation ID. Reuse only for an identical retry.');
  const hash=z.string().regex(/^[a-f0-9]{64}$/).describe('Original raw-byte SHA-256 from a file read such as fs_read or fs_read_chunk.');
  const sessionId = z.string().uuid().describe('Local Codex session_id returned by codex_session_list.');
  const device=z.string().uuid().describe('device_id from this server system_status/workspace_list. Confirm the intended device before mutations.');
  const outputSchema={ok:z.boolean(),source:z.object({device_id:z.string(),device_name:z.string(),instance_id:z.string()}),data:z.unknown().optional(),error:toolErrorSchema.optional()};
  function register(name:string,description:string,shape:z.ZodRawShape,readOnly:boolean,fn:(input:any)=>unknown,destructive=false,openWorld=false,nativeContent=false,metadata?:Record<string,unknown>) {
    app.diagnostics.registerTool(name);
    const guardedShape = readOnly ? shape : {...shape,expected_device_id:app.config.version===2?device:device.optional()};
    server.registerTool(name,{description,inputSchema:z.object(guardedShape).strict(),outputSchema,...(metadata?{_meta:metadata}:{}),
      annotations:{readOnlyHint:readOnly,destructiveHint:destructive,idempotentHint:readOnly||['fs_copy','fs_write','fs_write_binary','fs_write_binary_chunk','fs_import_file','fs_mkdir','fs_apply_patch','changes_restore','exec_start','checkpoint_save','task_create','task_checkpoint','task_export','fs_batch_apply','exec_write_stdin'].includes(name),openWorldHint:openWorld}
    },async(input)=>{
      try { return await app.runTool(async()=>{
      try{
        const {expected_device_id,...payload}=input as Record<string,unknown>;
        if(expected_device_id!==undefined && expected_device_id!==app.identity.deviceId)throw new AppError('DEVICE_MISMATCH','The request targets a different device. Read system_status and select the intended connection.');
        const output=await fn(payload);
        const transferred=nativeContent?output as Awaited<ReturnType<typeof app.fileTransfers.read>>:undefined;
        const result={ok:true,source:app.source(),data:transferred?transferred.data:output};
        return {content:[{type:'text' as const,text:JSON.stringify(result)},...(transferred?.content??[])],structuredContent:result};
      }
      catch(error){const result={...errorResult(error),source:app.source()};app.store.audit('tool_error',(input as any).workspace_id??null,{tool:name,code:result.error.code});return {isError:true,content:[{type:'text' as const,text:JSON.stringify(result)}],structuredContent:result};}
      }); } catch(error) {
        const result={...errorResult(error),source:app.source()};
        return {isError:true,content:[{type:'text' as const,text:JSON.stringify(result)}],structuredContent:result};
      }
    });
  }
  register('system_status','Inspect service capabilities and execution mode before using local development tools.',{},true,()=>app.status());
  register('fs_stat','Get the verified raw-byte SHA-256 and size of a local file, including PPTX/PDF/ZIP, without decoding or returning contents. For local copies use these hashes with fs_copy, which supports different workspaces and needs no upload or import. Also use before overwrites and to verify saved files.',{workspace_id:ws,path:rel},true,i=>app.files.stat(i));
  register('fs_copy','Copy an existing LOCAL file directly between authorized workspaces on this device. Use for requests such as copying a PDF from one local folder to another; do NOT upload, import, encode or parse the file. workspace_id/path select the DESTINATION; source_workspace_id/source_path select the SOURCE. Both paths are relative to their respective workspace roots. Get expected_source_sha256 with fs_stat. expected_sha256=null creates only; an authorized overwrite requires the destination hash. Source may be read-only; destination must be writable and its parent must exist. No URL, ChatGPT file object, command execution or script is required. Copies exact bytes with backups and verification. After a lost response inspect operation_status(tool=fs_copy) with the original key; do not replay an unknown write. Verify the target with fs_stat before reporting success.',{workspace_id:ws,path:rel,source_workspace_id:ws,source_path:rel,expected_source_sha256:hash,expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.localCopies.copy(i),true);
  register('operation_status','Inspect a durable single-file operation, including fs_copy, by its original idempotency_key. Returns recorded phase/receipt separately from current file observations and linked backup changes. Use after a lost response before any further write; unknown results must never be automatically replayed. Does not resume, restore or modify files. For batch writes use fs_batch_status.',{workspace_id:ws,expected_device_id:device,idempotency_key:key,tool:z.enum(['fs_copy','fs_import_file','fs_write_binary','fs_write','fs_apply_patch','changes_restore','fs_mkdir'])},true,i=>app.files.operationStatus(i));
  const inlineBinaryLimit=Math.min(app.config.limits.inlineBinaryWriteMaxBytes??262144,app.config.limits.binaryWriteMaxBytes??33554432);
  const {chunkMaxBytes:binaryChunkLimit,fileMaxBytes:binaryChunkFileLimit}=binaryChunkLimits(app.config);
  register('fs_write_binary_chunk',MODEL_RELAY_GUIDANCE+' Stage one ordered chunk of an existing original generated file as canonical Base64. Only when complete original slices fit host output/tool limits: Code Interpreter reads the existing bytes and computes full SHA-256 and size once, then returns each requested chunk and its SHA-256. Use one transfer key and unchanged path/whole-file hash/size/expected_sha256 for every chunk. Start offset_bytes=0 and follow next_offset; exact duplicate chunks are safe. Use exactly chunk_max_bytes bytes for every non-final chunk; only the final chunk may be shorter. Never output all chunks at once. The whole file must fit binaryWriteMaxBytes and the staging cache; the single-message inline limit does not apply. Default chunks are 64 KiB, configurable up to 256 KiB; query system_status for effective limits. Never resize images, downsample, reduce quality, reencode or regenerate to fit a limit. Receiving progress is NOT a saved file. The destination is written only after all bytes pass the original whole-file hash check; report success only for status=saved and verified=true. On lost responses inspect fs_write_binary_status. If resume_action=repeat_last_chunk, resend the original slice at retry_chunk_offset with retry_chunk_bytes and the same key; next_offset=total_bytes alone does not mean saved. Unknown final outcomes use operation_status with tool=fs_write_binary. Do not switch from an uncertain fs_import_file operation or regenerate the artifact. This transports model-supplied bytes, not a sandbox path; model context limits may still prevent completion.',{workspace_id:ws,path:rel,offset_bytes:z.number().int().min(0).max(binaryChunkFileLimit),content_base64:z.string().max(Math.ceil(binaryChunkLimit/3)*4),chunk_sha256:hash,content_sha256:hash,size_bytes:z.number().int().min(0).max(binaryChunkFileLimit),expected_sha256:hash.nullable(),idempotency_key:key.describe('One stable transfer key across all chunks; retry a chunk with the same offset and bytes.')},false,i=>app.binaryChunks.append(i),true);
  register('fs_write_binary_status','Inspect durable binary chunk transfer progress by its original key without uploading more data. A receiving transfer has no committed destination; continue at its next_offset with exactly chunk_max_bytes bytes except the shorter final chunk, only while the original file remains available. If resume_action=repeat_last_chunk, resend the original last slice using retry_chunk_offset/retry_chunk_bytes and the same key; do not infer success from next_offset=total_bytes. Saved receipts and current disk observations are separate. For unknown final writes do not replay; inspect operation_status with tool=fs_write_binary. Expired staging cannot be resumed automatically. status=blocked and resume_action=inspect_local_limits mean the current local configuration disallows continuing; report this without changing policy or starting a new key to bypass it.',{workspace_id:ws,expected_device_id:device,idempotency_key:key},true,i=>app.binaryChunks.status(i));
  register('fs_write_binary','Write exact supplied bytes encoded as canonical Base64. Small-file fallback when a generated file exists in Code Interpreter but the host only gives a sandbox:/ link. Read that existing file once in Code Interpreter and obtain COMPLETE Base64, original byte length and SHA-256; pass actual values, not a variable name, path or truncated output. Never resize, downsample, lower quality, reencode or regenerate to fit limits, or compute the expected digest from guessed data. This tool cannot resolve sandbox paths, access Code Interpreter memory or fetch attachments. The server cap is not a guarantee that ChatGPT can submit that much text. Stop if complete bytes are unavailable. First inspect any uncertain prior import with operation_status; do not replay across tools. Parent must exist. expected_sha256=null is create-only; use fs_stat before authorized overwrite. Reuse the same key for identical retries. Only verified=true proves the received bytes were saved, not that the file is valid or came from the claimed original. No HTTP, extension, widget or local command execution.',{workspace_id:ws,path:rel,content_base64:z.string().max(Math.ceil(inlineBinaryLimit/3)*4).describe('Complete canonical Base64 from the existing source bytes; no data URL or whitespace.'),content_sha256:hash.describe('SHA-256 computed from the original bytes by Code Interpreter before transferring them.'),size_bytes:z.number().int().min(0).max(inlineBinaryLimit),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.binaryInputs.write(i),true);
  register('fs_import_file','Legacy REMOTE file download only. For a file already on this computer use fs_copy directly, even across workspaces; do not upload it to ChatGPT or convert its local path into a file object. This importer requires an actual host-provided file object with an official HTTPS download_url and file_id. Never invent URLs or pass local/sandbox paths. For remote-only files without host forwarding fs_write_binary_chunk is an unverified fallback, only when complete original bytes and hashes can be relayed without truncation. Otherwise report the host limitation; do not retry URLs, increase chunks or restart services to bypass output truncation. Parent must exist; expected_sha256=null is create-only, authorized overwrite requires fs_stat hash. A verified receipt proves saved bytes. Inspect operation_status for uncertain results; renewed URLs may reuse the key only for identical file_id, destination and expected hash when recovery permits.',{workspace_id:ws,path:rel,file:chatGptFileSchema,expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.fileImports.import(i),true,true,false,{'openai/fileParams':['file']});
  register('codex_session_list','Find local Codex sessions by title/project path, optionally including archived history. Requires locally enabled session access. Read-only; does not run a Codex model. Follow next_cursor even when a filtered page is empty.',{query:z.string().max(200).optional(),workspace_id:ws.optional(),include_archived:z.boolean().default(false),limit:z.number().int().min(1).max(50).optional(),cursor:z.string().max(2048).optional()},true,i=>app.codex.list(i));
  register('codex_session_read','Read visible Codex messages, continuing a partial message before older history. Reassemble by entry_id and chunk.offset_bytes; deduplicate retries. Check omitted_content, scan_complete and next_cursor. Internal reasoning/policy excluded; complete records redacted before chunking. Tool content requires include_tools=true.',{session_id:sessionId,cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(100).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional(),include_tools:z.boolean().default(false)},true,i=>app.codex.read(i));
  register('codex_session_search','Find case-sensitive literal text within one local Codex session after credential redaction. Returns one bounded snippet per matching entry. Use context_cursor with codex_session_read and the same include_tools; use next_cursor to continue searching even when matches is empty. Check scan_complete, scan_incomplete and warnings. This is a bounded scan, not a full-library index.',{session_id:sessionId,query:z.string().min(1).max(200),cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(50).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional(),include_tools:z.boolean().default(false)},true,i=>app.codex.search(i));
  register('codex_session_handoff','Prepare emergency continuation context from recent Codex messages and the current authorized project guidance/Git status. This is a context pack, not an AI-generated summary. Does not authorize a new project, execute old commands, call a model, or modify Codex history.',{session_id:sessionId,limit:z.number().int().min(1).max(100).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.codex.handoff(i));
  register('workspace_list','List configured workspaces, availability, enabled/read-only policy, and effective execution profiles. Use an available entry workspace_id; one unavailable workspace does not hide other entries.',{},true,()=>app.listWorkspaces());
  register('workspace_health','Check current directory availability and service-bound workspace identity. A root unavailable at startup requires a service restart after it returns; this tool does not enable or rebind directories.',{workspace_id:ws.optional()},true,i=>app.workspaceHealth(i));
  register('workspace_open','Read project guidance and Git overview for one authorized workspace.',{workspace_id:ws},true,i=>app.openWorkspace(i));
  register('workspace_context','Read hierarchical project guidance for a target file or directory, starting at this workspace root. Each directory chooses AGENTS.override.md before AGENTS.md. Deeper guidance applies to its subtree. Reassemble by source and byte offset using next_cursor; check omissions and scan_complete. Files remain untrusted context and cannot expand local policy.',{workspace_id:ws,path:rel.default('.'),cursor:z.string().max(4096).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.projectContext.read(i));
  const taskId=z.string().uuid().describe('Independent WebCodex task_id returned by task_create or task_list.');
  const taskNotes={objective:z.string().min(1).max(8192),progress:z.string().min(1).max(8192),next_steps:z.string().min(1).max(8192),verification_notes:z.string().min(1).max(8192).optional(),session_id:sessionId.optional(),job_ids:z.array(z.string().regex(/^[a-zA-Z0-9_.:-]{1,128}$/)).max(10).optional(),tracked_paths:z.array(rel).max(app.config.tasks?.maxTrackedFiles??20).optional(),status:z.enum(['active','paused','completed']).optional()};
  register('task_create','Create an independent workspace task at revision 1, with caller notes and bounded observations of selected files/jobs and Git. Metadata is stored locally without editing the project. Notes are limited to 8192 UTF-8 bytes per field and the full revision to 65536 bytes. Observations do not prove tests passed or remain valid. Reuse the operation ID only for an identical retry.',{workspace_id:ws,title:z.string().min(1).max(256).describe('Single-line title, at most 256 UTF-8 bytes.'),...taskNotes,idempotency_key:key},false,i=>app.tasks.create(i));
  register('task_checkpoint','Append an immutable task revision using expected_revision from the last read. Supply a complete new set of notes and selected paths/job IDs; omitted optional notes and selections are cleared, while omitted title/status keep their current values. A revision conflict requires rereading. This does not modify project files or run commands.',{workspace_id:ws,task_id:taskId,expected_revision:z.number().int().positive(),title:z.string().min(1).max(256).optional(),...taskNotes,idempotency_key:key},false,i=>app.tasks.checkpoint(i));
  register('task_list','List bounded task summaries for this device/workspace, ordered by recent update. Follow next_offset; concurrent updates may shift pages. Use task_read to obtain notes and immutable revisions.',{workspace_id:ws,limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().nonnegative().optional()},true,i=>app.tasks.list(i));
  register('task_read','Read an immutable task revision as paginated JSON. Concatenate content by chunk.offset_bytes before parsing; next_cursor pins the revision even if a newer one is saved. The first page includes bounded current freshness observations; later pages return freshness=null. Unchanged observations never prove test validity. Check coverage and omitted details. Cursors expire on service restart.',{workspace_id:ws,task_id:taskId,revision:z.number().int().positive().optional(),cursor:z.string().max(4096).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.tasks.read(i));
  register('task_export','Export a selected immutable task revision to WEBCODEX_HANDOFF.md with hash checking and a recorded backup. Read the existing file first; expected_sha256=null is create-only. Preserves saved observations as historical facts; does not rerun commands or change Codex history.',{workspace_id:ws,task_id:taskId,revision:z.number().int().positive().optional(),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.tasks.export(i),true);
  register('checkpoint_read','Read the saved WEBCODEX_HANDOFF.md in this workspace. Missing files return exists=false and sha256=null. Known credentials are redacted before output limits; line numbers refer to redacted text. Use the raw-byte sha256 for a later checkpoint_save. Check truncated and next_start_line.',{workspace_id:ws,start_line:z.number().int().positive().optional(),end_line:z.number().int().positive().optional()},true,i=>app.checkpoints.read(i));
  register('checkpoint_save','Create or update WEBCODEX_HANDOFF.md with caller-supplied task notes, current filtered Git status and real observations of selected WebCodex jobs. The file is backed up and hash-checked; read it first. No model runs, no Codex history changes, and no commands are executed. Caller notes are not verified test results. Pass a new operation ID for a fresh snapshot; reuse only for an identical retry.',{workspace_id:ws,objective:z.string().min(1).max(8192),progress:z.string().min(1).max(8192),next_steps:z.string().min(1).max(8192),verification_notes:z.string().min(1).max(8192).optional(),session_id:sessionId.optional(),job_ids:z.array(z.string().regex(/^[a-zA-Z0-9_.:-]{1,128}$/)).max(10).optional(),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.checkpoints.save(i),true);
  register('fs_list','List one directory with bounded pagination. '+FILE_ROUTES.text+' '+FILE_ROUTES.pdf,{workspace_id:ws,path:rel.default('.'),cursor:z.number().int().nonnegative().optional(),limit:z.number().int().positive().max(1000).optional()},true,i=>app.files.list(i));
  register('fs_read_file',FILE_ROUTES.raw+' '+FILE_ROUTES.pdf+' '+FILE_ROUTES.diagnostic+' Preserve original bytes; no server-side conversion, OCR or truncation. Embedded URIs are snapshot identifiers, not public download URLs. Oversized files fail as a whole. Use name/display_name for the filename.',{workspace_id:ws,path:rel},true,i=>app.fileTransfers.read(i),false,false,true);
  register('fs_read','Read a bounded line range and raw-byte SHA-256. Use the hash for conflict-safe edits. Use fs_read_chunk for FILE_TOO_LARGE or line_cut; do not repeat a cut line expecting the missing tail. Text only.',{workspace_id:ws,path:rel,start_line:z.number().int().positive().optional(),end_line:z.number().int().positive().optional()},true,i=>app.files.read(i));
  register('fs_read_chunk','Read large text files or long lines with a signed next_cursor. Reassemble content by decoded UTF-8 byte offset. Raw sha256 identifies the whole file. Each page validates the bounded full source; edits, replacements and service restarts invalidate the cursor. Read limit does not increase the write limit.',{workspace_id:ws,path:rel,cursor:z.string().max(4096).optional(),max_bytes:z.number().int().min(256).max(app.config.limits.readMaxBytes).optional()},true,i=>app.fileChunks.read(i));
  register('fs_read_many','Read 1–16 related text files with a shared content-byte budget. Each result has its own success or error. Check truncated and omitted entries; file hashes always identify original bytes.',{workspace_id:ws,files:z.array(z.object({path:rel,start_line:z.number().int().positive().optional(),end_line:z.number().int().positive().optional()}).strict()).min(1).max(16),max_total_bytes:z.number().int().positive().max(app.config.limits.readMaxBytes).optional()},true,i=>app.files.readMany(i));
  const batchChanges=z.array(z.discriminatedUnion('op',[
    z.object({op:z.literal('write'),path:rel,content:z.string().max(app.config.limits.writeMaxBytes),expected_sha256:hash.nullable()}).strict(),
    z.object({op:z.literal('patch'),path:rel,patch:z.string().max(patchInputMaxBytes(app.config.limits.writeMaxBytes)),expected_sha256:hash}).strict(),
    z.object({op:z.literal('delete'),path:rel,expected_sha256:hash}).strict(),
    z.object({op:z.literal('move'),path:rel,to:rel.describe('Unused destination path in the same workspace; its parent must exist.'),expected_sha256:hash}).strict(),
    z.object({op:z.literal('copy'),path:rel,to:rel.describe('Unused destination path in the same workspace; its parent must exist.'),expected_sha256:hash}).strict()
  ])).min(1).max(app.config.fileBatches?.maxFiles??20);
  register('fs_batch_preview','Copy an existing local file within the same workspace with op=copy, then fs_batch_apply; no script, upload, Base64 or import is needed and execution may remain disabled. Also previews text writes/patches and raw-byte deletes/moves. Read source hashes first (fs_stat for binary). Copy/move destinations must not exist. Every affected path may appear only once; a move or copy counts as two paths. Binary operations return metadata and use binary byte limits. Returns changes, bounded diff with omissions, and plan_sha256. Does not persist a plan or change files. Check all changes and diff_truncated before applying.',{workspace_id:ws,changes:batchChanges,max_bytes:z.number().int().min(1).max(app.config.limits.readMaxBytes).optional()},true,i=>app.fileBatches.preview(i));
  register('fs_batch_apply','Apply exactly the changes inspected with fs_batch_preview; submit its plan_sha256 as expected_plan_sha256. Revalidates all hashes and saves backups before writes. Files change sequentially; this is not an OS-atomic transaction. Always inspect data.status: applied means completed; rolled_back or partial means the batch failed, even when ok=true. On errors or lost responses use fs_batch_status with this operation key. Never blindly start a new operation after an uncertain result.',{workspace_id:ws,changes:batchChanges,expected_plan_sha256:hash,idempotency_key:key},false,i=>app.fileBatches.apply(i),true);
  register('fs_batch_status','Inspect the durable batch journal by its original idempotency_key and compare current file hashes with the before/after versions. Recorded progress and current observations are separate facts; matching hashes do not prove authorship. Unknown or partial batches are never automatically resumed. This tool does not restore files; review change IDs and use existing restoration tools after checking current versions.',{workspace_id:ws,idempotency_key:key},true,i=>app.fileBatches.status(i));
  register('fs_search','Search authorized project text with ripgrep. Returns bounded matches; skips protected paths and large dependency directories.',{workspace_id:ws,query:z.string().min(1).max(2048),path:rel.default('.'),regex:z.boolean().default(false),case_sensitive:z.boolean().default(false),max_results:z.number().int().positive().max(1000).optional()},true,i=>app.files.search(i));
  register('fs_write','Save generated SVG diagrams, HTML, Markdown, XML or source code to the local workspace as text; command execution may remain disabled. Parent directories must exist (use fs_mkdir if needed). expected_sha256=null is create-only; existing files require their original hash. Backups and conflict checks are enforced. Read back to verify before reporting saved.',{workspace_id:ws,path:rel,content:z.string().max(app.config.limits.writeMaxBytes),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.files.write(i),true);
  register('fs_mkdir','Create one directory within the authorized workspace. Parent must already exist. Reuse the operation ID only for an identical retry.',{workspace_id:ws,path:rel,idempotency_key:key},false,i=>app.files.mkdir(i));
  register('fs_apply_patch','Apply a strict single-file unified diff after reading its hash. Patch input allows up to twice writeMaxBytes in UTF-8 bytes, consistently with batch patches; the resulting file remains limited to writeMaxBytes. dry_run previews without writing; still classified as write-capable.',{workspace_id:ws,path:rel,patch:z.string().max(patchInputMaxBytes(app.config.limits.writeMaxBytes)),expected_sha256:hash,idempotency_key:key,dry_run:z.boolean().default(false)},false,i=>app.files.applyPatch(i),true);
  register('changes_list','List recorded service edits for this workspace; these do not include arbitrary shell side effects.',{workspace_id:ws,limit:z.number().int().positive().max(100).optional(),cursor:z.number().int().nonnegative().optional()},true,i=>app.files.changesList(i));
  register('changes_preview','Preview undoing one recorded edit without changing files. Returns a bounded diff from the current file to its saved previous version. Requires the current file to match the recorded after-version. Check truncated before deciding to restore.',{workspace_id:ws,change_id:z.string().min(1).max(128),context_lines:z.number().int().min(0).max(20).optional(),max_bytes:z.number().int().positive().max(app.config.limits.readMaxBytes).optional()},true,i=>app.files.changeDiff(i));
  register('changes_restore','Undo one recorded file edit only when the current file matches expected_sha256. Does not undo shell, network or database side effects.',{workspace_id:ws,change_id:z.string().min(1).max(128),expected_sha256:hash.nullable(),idempotency_key:key},false,i=>app.files.restore(i),true);
  register('git_status','Inspect local repository changes using Git porcelain output; does not stage or commit.',{workspace_id:ws},true,i=>app.git.status(i));
  register('git_diff','Read a bounded Git diff. External diff, text conversions and submodule traversal are disabled.',{workspace_id:ws,staged:z.boolean().default(false)},true,i=>app.git.diff(i));
  register('exec_start','Run a native program with host-user privileges. Check command_policy: all accepts installed names, absolute executable paths and presets; allowlist requires workspace aliases. For Windows copy/dir call executable=cmd.exe with args=["/d","/c",command]; quote paths in command. No script file or Node program is required. Other programs receive separate args; .cmd/.bat require an explicit interpreter. Preset args are prepended. Local commands cannot read ChatGPT sandbox:/ files. Requires trusted-host execution and a writable workspace, with possible file/network effects. Receipts bind program, policy and environment. stdin=pipe enables exec_write_stdin. Inspect the job terminal status and exit_code, then fs_stat for copied hashes; receipt alone does not prove copying.',{workspace_id:ws,executable:z.string().min(1).max(4096).refine(value=>!/[\x00-\x1f\x7f]/.test(value)),args:z.array(z.string().max(8192)).max(128).default([]),cwd:rel.default('.'),timeout_ms:z.number().int().positive().max(86400000).optional(),stdin:z.enum(['closed','pipe']).default('closed'),idempotency_key:key},false,i=>app.jobs.start(i),true,true);
  register('ssh_readonly_probe','Run one bounded, fixed-command SSH diagnostic against a locally configured remote. The probe kind is an enum and cannot contain a shell command; no remote files are modified. Configure remotes in .webcodex/config.json (host, port, user, identityFile, strictHostKeyChecking, optional projectRoot). Requires trusted-host execution and the local ssh program; host-key verification remains enabled by default. Use this tool for H20/4090D status checks instead of exec_start.',{remote_id:z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/).describe('Key under remotes in the local configuration.'),probe:z.enum(['identity','roots','project_candidates','git_status','processes','gpu','directory_listing']),timeout_ms:z.number().int().min(1000).max(120000).optional()},true,i=>app.sshReadonly.probe(i),false,true);
  register('exec_write_stdin','Send UTF-8 text and/or end=true (EOF) to a running job started with stdin=pipe by this service. Requires current write authorization, trusted-host mode, and the same execution profile/program/environment as the original job. Reuse an operation key only for an identical retry; after unknown delivery do not resend with a new key. Success only means bytes were written to the OS pipe, not processed by the program. Input text is not persisted/audited by this input tool, but the child may echo or store it. Per-call and cumulative byte limits apply.',{workspace_id:ws,job_id:z.string().min(1).max(128),content:z.string().max(app.config.execution.stdinMaxBytes??65536).optional(),end:z.boolean().optional(),idempotency_key:key},false,i=>app.jobs.writeStdin(i),true,true);
  register('exec_poll','Read new stdout/stderr using the last next_cursor. Check final status and exit_code; an empty chunk does not mean the job completed.',{workspace_id:ws,job_id:z.string().min(1).max(128),cursor:z.number().int().nonnegative().default(0),max_bytes:z.number().int().min(4).max(65536).default(16384)},true,i=>app.jobs.poll(i));
  register('exec_list','List persisted jobs for an authorized workspace, including interrupted or unknown jobs.',{workspace_id:ws,limit:z.number().int().positive().max(100).optional()},true,i=>app.jobs.list(i));
  register('exec_wait','Wait briefly for new persisted job output or terminal status, then return the same cursor-based output as exec_poll. wait_reason=timeout only ends this wait; it does not cancel the command. Use next_cursor for the next wait/poll. Inspect final status and exit_code before reporting a result.',{workspace_id:ws,job_id:z.string().min(1).max(128),cursor:z.number().int().nonnegative().optional(),max_bytes:z.number().int().min(4).max(app.config.limits.readMaxBytes).optional(),wait_ms:z.number().int().min(0).max(Math.min(20000,app.config.execution.maxWaitMs??20000)).optional()},true,i=>app.jobs.wait(i));
  register('exec_tail','Read the bounded end of persisted job logs, optionally filtered to stdout or stderr, in chronological order. This may omit earlier or other-stream output. Storage truncation can mean the latest actual process output was not persisted. next_cursor is the global persisted end for future unfiltered exec_poll/exec_wait; tail does not establish success.',{workspace_id:ws,job_id:z.string().min(1).max(128),stream:z.enum(['all','stdout','stderr']).optional(),max_bytes:z.number().int().min(4).max(app.config.limits.readMaxBytes).optional()},true,i=>app.jobs.tail(i));
  register('exec_cancel','Stop a job owned by this service and its child processes. Partial side effects are possible.',{workspace_id:ws,job_id:z.string().min(1).max(128)},false,i=>app.jobs.cancel(i),true);
  for (const name of ['fs_open_file','file_widget_probe','file_widget_read','file_widget_release']) app.diagnostics.registerTool(name);
  registerFileWidgetProbe(server, app);
  registerReadingRelayProbe(server, app);
  registerDocumentTools(server, app);
  registerFileSaveTools(server, app);
  return server;
}
